name = "jwk-store"
compatibility_date = "2023-01-01"

[[kv_namespaces]]
binding = "STORAGE"
id = "<YOUR_KV_NAMESPACE_ID>"

[[r2_buckets]]
binding = 'CDN_BUCKET'
bucket_name = '<YOUR_R2_PUBLIC_BUCKET>'